name: mobile_app
description: "HRIS Mobile App - Employee Self Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  
  # Routing
  auto_route: ^7.9.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Auth
  google_sign_in: ^6.2.1
  
  # Location (for GPS clock-in)
  geolocator: ^11.0.0
  
  # Utilities
  connectivity_plus: ^6.0.3
  intl: ^0.20.2
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
